namespace :bootstrap do
  desc "Add the default user"
  task :default_user => :environment do
    User.create( :username => 'admin', :password => 'default' )
  end

  desc "Add Default Salary Heads"
  task :salary_head => :environment do
    SalaryHead.create( :head_name => 'Basic', :short_name => 'BASIC', :salary_type => "Earnings" )
    SalaryHead.create( :head_name => 'PF', :short_name => 'PF', :salary_type => "Deductions" )
    SalaryHead.create( :head_name => 'ESI', :short_name => 'ESI', :salary_type => "Deductions" )
  end

  desc "Add States"
  task :state => :environment do
    State.create( :state_name => 'Andaman and Nicobar Islands')
    State.create( :state_name => 'Andhra Pradesh')
    State.create( :state_name => 'Arunachal Pradesh')
    State.create( :state_name => 'Assam')
    State.create( :state_name => 'Bihar')
    State.create( :state_name => 'Chandigarh')
    State.create( :state_name => 'Dadra and Nagar Haveli')
    State.create( :state_name => 'Daman and Diu')
    State.create( :state_name => 'Delhi')
    State.create( :state_name => 'Goa')
    State.create( :state_name => 'Gujarat')
    State.create( :state_name => 'Haryana')
    State.create( :state_name => 'Himachal Pradesh')
    State.create( :state_name => 'Jammu and Kashmir')
    State.create( :state_name => 'Karnataka')
    State.create( :state_name => 'Kerala')
    State.create( :state_name => 'Lakhswadeep')
    State.create( :state_name => 'Madhya Pradesh')
    State.create( :state_name => 'Maharashtra')
    State.create( :state_name => 'Manipur')
    State.create( :state_name => 'Meghalaya')
    State.create( :state_name => 'Mizoram')
    State.create( :state_name => 'Nagaland')
    State.create( :state_name => 'Orissa')
    State.create( :state_name => 'Pondicherry')
    State.create( :state_name => 'Punjab')
    State.create( :state_name => 'Rajasthan')
    State.create( :state_name => 'Sikkim')
    State.create( :state_name => 'Tamilnadu')
    State.create( :state_name => 'Tripura')
    State.create( :state_name => 'Uttar Pradesh')
    State.create( :state_name => 'West Bengal')
    State.create( :state_name => 'Chhatishgarh')
    State.create( :state_name => 'Uttaranchal')
    State.create( :state_name => 'Jharkhand')
  end

  desc "Add Default Attendance Configuration"
  task :attendance_configuration => :environment do
    AttendanceConfiguration.create( :attendance => '<Master List>', :short_name => 'MASTER', :salary_calendar_days => "Actual Day / Month" )
  end

  desc "Add Default Financial Institution"
  task :financial_institution => :environment do
    FinancialInstitution.create( :name => "CASH", :address_line1 => "address", :address_line2 => "address", :address_line3 => "address", :address_line4 => "address", :pincode => 560076, :branch_code => "branch_code", :email => "email" )
  end

  desc "Add Default Classification Designation"
  task :classification_heading => :environment do
    ClassificationHeading.create( :classification_heading_name => "Designation", :display_order => 1 )
    ClassificationHeading.create( :classification_heading_name => "Occupation", :display_order => 2 )
    ClassificationHeading.create( :classification_heading_name => "Department", :display_order => 3 )
    ClassificationHeading.create( :classification_heading_name => "Division", :display_order => 4 )
    ClassificationHeading.create( :classification_heading_name => "Grade", :display_order => 5 )
    ClassificationHeading.create( :classification_heading_name => "Section", :display_order => 6 )
  end

  desc "Add Default HR Categories"
  task :hr_category => :environment do
    desc "Creating HR Category Personal"
    personal = HrCategory.create(:category_name => "Personal")
    desc "Creating HR Category Details for Hr Category Personal"
    HrCategoryDetail.create(:hr_category_id => personal.id, :name => "Blood Group", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => personal.id, :name => "Cast Category", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => personal.id, :name => "Qualification", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => personal.id, :name => "Nationality", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => personal.id, :name => "Driving Lic No", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => personal.id, :name => "Language Known", :data_type => "String", :required => false)

    desc "Creating HR Category Passport"
    passport = HrCategory.create(:category_name => "Passport")
    desc "Creating HR Category Details for Hr Category 'Passport'"
    HrCategoryDetail.create(:hr_category_id => passport.id, :name => "Number", :data_type => "Integer", :required => false)
    HrCategoryDetail.create(:hr_category_id => passport.id, :name => "Issued At", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => passport.id, :name => "Issued date", :data_type => "Date", :required => false)
    HrCategoryDetail.create(:hr_category_id => passport.id, :name => "Expiry Date", :data_type => "String", :required => false)


    desc "Creating HR Category Family"
    family = HrCategory.create(:category_name => "Family")
    desc "Creating HR Category Details for Hr Category 'Family'"
    HrCategoryDetail.create(:hr_category_id => family.id, :name => "Name Of Relative", :data_type => "String", :required => true)
    HrCategoryDetail.create(:hr_category_id => family.id, :name => "Relation", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => family.id, :name => "Remarks", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => family.id, :name => "Date of Birth", :data_type => "Date", :required => false)
    HrCategoryDetail.create(:hr_category_id => family.id, :name => "Dependent", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => family.id, :name => "Nominee", :data_type => "String", :required => false)

    desc "Creating HR Category Education"
    education = HrCategory.create(:category_name => "Education")
    desc "Creating HR Category Details for Hr Category 'Education'"
    HrCategoryDetail.create(:hr_category_id => education.id, :name => "Qualification", :data_type => "String", :required => true)
    HrCategoryDetail.create(:hr_category_id => education.id, :name => "University", :data_type => "String", :required => true)
    HrCategoryDetail.create(:hr_category_id => education.id, :name => "Remarks", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => education.id, :name => "Percentage", :data_type => "Decimal", :required => false)
    HrCategoryDetail.create(:hr_category_id => education.id, :name => "Year Passed", :data_type => "Integer", :required => false)

    desc "Creating HR Category Training"
    training = HrCategory.create(:category_name => "Training")
    desc "Creating HR Category Details for Hr Category 'Training'"
    HrCategoryDetail.create(:hr_category_id => training.id, :name => "Training Name", :data_type => "String", :required => true)
    HrCategoryDetail.create(:hr_category_id => training.id, :name => "Location", :data_type => "String", :required => true)
    HrCategoryDetail.create(:hr_category_id => training.id, :name => "Comments", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => training.id, :name => "Remarks", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => training.id, :name => "From Date", :data_type => "Date", :required => false)
    HrCategoryDetail.create(:hr_category_id => training.id, :name => "To Date", :data_type => "Date", :required => false)

    desc "Creating HR Category Accident"
    accident = HrCategory.create(:category_name => "Accident")
    desc "Creating HR Category Details for Hr Category 'Accident'"
    HrCategoryDetail.create(:hr_category_id => accident.id, :name => "Accident", :data_type => "String", :required => true)
    HrCategoryDetail.create(:hr_category_id => accident.id, :name => "Location", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => accident.id, :name => "Compensation", :data_type => "Integer", :required => false)
    HrCategoryDetail.create(:hr_category_id => accident.id, :name => "Remarks", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => accident.id, :name => "Date", :data_type => "Date", :required => false)

    desc "Creating HR Category Disciplinary Actions"
    disciplinary_actions = HrCategory.create(:category_name => "Disciplinary Actions")
    desc "Creating HR Category Details for Hr Category 'Disciplinary Actions'"
    HrCategoryDetail.create(:hr_category_id => disciplinary_actions.id, :name => "Memo", :data_type => "String", :required => true)
    HrCategoryDetail.create(:hr_category_id => disciplinary_actions.id, :name => "Issued By", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => disciplinary_actions.id, :name => "Comments", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => disciplinary_actions.id, :name => "Remarks", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => disciplinary_actions.id, :name => "Issued Date", :data_type => "Date", :required => false)

    desc "Creating HR Category Extracurricular Event"
    extracurricular_event = HrCategory.create(:category_name => "Extracurricular Event")
    desc "Creating HR Category Details for Hr Category 'Extracurricular Event'"
    HrCategoryDetail.create(:hr_category_id => extracurricular_event.id, :name => "Game/Activity", :data_type => "String", :required => true)
    HrCategoryDetail.create(:hr_category_id => extracurricular_event.id, :name => "Event", :data_type => "String", :required => true)
    HrCategoryDetail.create(:hr_category_id => extracurricular_event.id, :name => "Remarks", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => extracurricular_event.id, :name => "From Date", :data_type => "Date", :required => false)
    HrCategoryDetail.create(:hr_category_id => extracurricular_event.id, :name => "To Date", :data_type => "Date", :required => false)

    desc "Creating HR Category Extracurricular Award"
    extracurricular_award = HrCategory.create(:category_name => "Extracurricular Award")
    desc "Creating HR Category Details for Hr Category 'Extracurricular Award'"
    HrCategoryDetail.create(:hr_category_id => extracurricular_award.id, :name => "Game/Activity", :data_type => "String", :required => true)
    HrCategoryDetail.create(:hr_category_id => extracurricular_award.id, :name => "Award", :data_type => "String", :required => true)
    HrCategoryDetail.create(:hr_category_id => extracurricular_award.id, :name => "Remarks", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => extracurricular_award.id, :name => "Date", :data_type => "Date", :required => false)

    desc "Creating HR Category General"
    general = HrCategory.create(:category_name => "General")
    desc "Creating HR Category Details for Hr Category 'General'"
    HrCategoryDetail.create(:hr_category_id => general.id, :name => "Description", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => general.id, :name => "Details", :data_type => "String", :required => false)
    HrCategoryDetail.create(:hr_category_id => general.id, :name => "Date", :data_type => "Date", :required => false)
  end

  desc "Add Country and their respective currency"
  task :country => :environment do
    Country.create( :name => "Afghanistan", :currency => "Afghanistan Afghani")
    Country.create( :name => "Albania", :currency => "Albanian Lek")
    Country.create( :name => "Algeria", :currency => "Algerian Dinar")
    Country.create( :name => "Angola", :currency => "Angolan New Kwanza")
    Country.create( :name => "United Arab Emirates", :currency => "Arab Emirates Dirham")
    Country.create( :name => "Argentina", :currency => "Argentine Peso")
    Country.create( :name => "Armenia", :currency => "Armenian Dram")
    Country.create( :name => "Aruba", :currency => "Aruban Guilder")
    Country.create( :name => "Australia", :currency => "Australian Dollar")
    Country.create( :name => "Cocos (Keeling) Islands", :currency => "Australian Dollar")
    Country.create( :name => "Kiribati", :currency => "Australian Dollar")
    Country.create( :name => "Nauru", :currency => "Australian Dollar")
    Country.create( :name => "Norfolk Island", :currency => "Australian Dollar")
    Country.create( :name => "Tuvalu", :currency => "Australian Dollar")
    Country.create( :name => "Christmas Island", :currency => "Australian Dollar")
    Country.create( :name => "Heard Island and McDonald Islands", :currency => "Australian Dollar")
    Country.create( :name => "Azerbaijan", :currency => "Azerbaijanian Manat")
    Country.create( :name => "Bahamas", :currency => "Bahamian Dollar")
    Country.create( :name => "Bahrain", :currency => "Bahraini Dinar")
    Country.create( :name => "Bangladesh", :currency => "Bangladeshi Taka")
    Country.create( :name => "Barbados", :currency => "Barbados Dollar")
    Country.create( :name => "Belarus", :currency => "Belarussian Ruble")
    Country.create( :name => "Belize", :currency => "Belize Dollar")
    Country.create( :name => "Bermuda", :currency => "Bermudian Dollar")
    Country.create( :name => "Bhutan", :currency => "Bhutan Ngultrum")
    Country.create( :name => "Bolivia", :currency => "Boliviano")
    Country.create( :name => "Botswana", :currency => "Botswana Pula")
    Country.create( :name => "Brazil", :currency => "Brazilian Real")
    Country.create( :name => "Brunei Darussalam", :currency => "Brunei Dollar")
    Country.create( :name => "Bulgaria", :currency => "Bulgarian Lev")
    Country.create( :name => "Burundi", :currency => "Burundi Franc")
    Country.create( :name => "Senegal", :currency => "CFA Franc BCEAO")
    Country.create( :name => "Mali", :currency => "CFA Franc BCEAO")
    Country.create( :name => "Burkina Faso", :currency => "CFA Franc BCEAO")
    Country.create( :name => "Benin", :currency => "CFA Franc BCEAO")
    Country.create( :name => "Ivory Coast", :currency => "CFA Franc BCEAO")
    Country.create( :name => "Togo", :currency => "CFA Franc BCEAO")
    Country.create( :name => "Niger", :currency => "CFA Franc BCEAO")
    Country.create( :name => "Chad", :currency => "CFA Franc BCEAO")
    Country.create( :name => "Equatorial Guinea", :currency => "CFA Franc BCEAO")
    Country.create( :name => "Congo", :currency => "CFA Franc BCEAO")
    Country.create( :name => "Gabon", :currency => "CFA Franc BCEAO")
    Country.create( :name => "Cameroon", :currency => "CFA Franc BCEAO")
    Country.create( :name => "Central African Republic", :currency => "CFA Franc BCEAO")
    Country.create( :name => "Wallis and Futuna Islands", :currency => "CFP Franc")
    Country.create( :name => "Polynesia (French)", :currency => "CFP Franc")
    Country.create( :name => "New Caledonia (French)", :currency => "CFP Franc")
    Country.create( :name => "Canada", :currency => "Canadian Dollar")
    Country.create( :name => "Cape Verde", :currency => "Cape Verde Escudo")
    Country.create( :name => "Cayman Islands", :currency => "Cayman Islands Dollar")
    Country.create( :name => "Chile", :currency => "Chilean Peso")
    Country.create( :name => "Colombia", :currency => "Colombian Peso")
    Country.create( :name => "Comoros", :currency => "Comoros Franc")
    Country.create( :name => "Costa Rica", :currency => "Costa Rican Colon")
    Country.create( :name => "Croatia", :currency => "Croatian Kuna")
    Country.create( :name => "Cuba", :currency => "Cuban Peso")
    Country.create( :name => "Cyprus", :currency => "Cyprus Pound")
    Country.create( :name => "Czech Rep.", :currency => "Czech Koruna")
    Country.create( :name => "Denmark", :currency => "Danish Krone")
    Country.create( :name => "Faroe Islands", :currency => "Danish Krone")
    Country.create( :name => "Greenland", :currency => "Danish Krone")
    Country.create( :name => "Macedonia", :currency => "Denar")
    Country.create( :name => "Serbia", :currency => "Dinar")
    Country.create( :name => "Djibouti", :currency => "Djibouti Franc")
    Country.create( :name => "Sao Tome and Principe", :currency => "Dobra")
    Country.create( :name => "Dominican Republic", :currency => "Dominican Peso")
    Country.create( :name => "Dominica", :currency => "East Caribbean Dollar")
    Country.create( :name => "Saint Vincent & Grenadines", :currency => "East Caribbean Dollar")
    Country.create( :name => "Antigua and Barbuda", :currency => "East Caribbean Dollar")
    Country.create( :name => "Saint Lucia", :currency => "East Caribbean Dollar")
    Country.create( :name => "Anguilla", :currency => "East Caribbean Dollar")
    Country.create( :name => "Montserrat", :currency => "East Caribbean Dollar")
    Country.create( :name => "Saint Kitts & Nevis Anguilla", :currency => "East Caribbean Dollar")
    Country.create( :name => "Antarctica", :currency => "East Caribbean Dollar")
    Country.create( :name => "Grenada", :currency => "East Caribbean Dollar")
    Country.create( :name => "Ecuador", :currency => "Ecuador Sucre")
    Country.create( :name => "Egypt", :currency => "Egyptian Pound")
    Country.create( :name => "El Salvador", :currency => "El Salvador Colon")
    Country.create( :name => "Eritrea", :currency => "Eritrean Nakfa")
    Country.create( :name => "Estonia", :currency => "Estonian Kroon")
    Country.create( :name => "Ethiopia", :currency => "Ethiopian Birr")
    Country.create( :name => "Greece", :currency => "Euro")
    Country.create( :name => "Spain", :currency => "Euro")
    Country.create( :name => "European Union", :currency => "Euro")
    Country.create( :name => "Guadeloupe (French)", :currency => "Euro")
    Country.create( :name => "Martinique (French)", :currency => "Euro")
    Country.create( :name => "Vatican", :currency => "Euro")
    Country.create( :name => "Andorra", :currency => "Euro")
    Country.create( :name => "Finland", :currency => "Euro")
    Country.create( :name => "France", :currency => "Euro")
    Country.create( :name => "French Guiana", :currency => "Euro")
    Country.create( :name => "French Southern Territories", :currency => "Euro")
    Country.create( :name => "Austria", :currency => "Euro")
    Country.create( :name => "Luxembourg", :currency => "Euro")
    Country.create( :name => "Portugal", :currency => "Euro")
    Country.create( :name => "Reunion (French)", :currency => "Euro")
    Country.create( :name => "Belgium", :currency => "Euro")
    Country.create( :name => "Monaco", :currency => "Euro")
    Country.create( :name => "Germany", :currency => "Euro")
    Country.create( :name => "Saint Pierre and Miquelon", :currency => "Euro")
    Country.create( :name => "Mayotte", :currency => "Euro")
    Country.create( :name => "Ireland", :currency => "Euro")
    Country.create( :name => "Netherlands", :currency => "Euro")
    Country.create( :name => "Montenegro", :currency => "Euro")
    Country.create( :name => "Italy", :currency => "Euro")
    Country.create( :name => "Falkland Islands", :currency => "Falkland Islands Pound")
    Country.create( :name => "Fiji", :currency => "Fiji Dollar")
    Country.create( :name => "Congo, Dem. Republic", :currency => "Francs")
    Country.create( :name => "Gambia", :currency => "Gambian Dalasi")
    Country.create( :name => "Georgia", :currency => "Georgian Lari")
    Country.create( :name => "Ghana", :currency => "Ghanaian Cedi")
    Country.create( :name => "Gibraltar", :currency => "Gibraltar Pound")
    Country.create( :name => "Guinea", :currency => "Guinea Franc")
    Country.create( :name => "Guinea Bissau", :currency => "Guinea-Bissau Peso")
    Country.create( :name => "Haiti", :currency => "Haitian Gourde")
    Country.create( :name => "Honduras", :currency => "Honduran Lempira")
    Country.create( :name => "Hong Kong", :currency => "Hong Kong Dollar")
    Country.create( :name => "Hungary", :currency => "Hungarian Forint")
    Country.create( :name => "Iceland", :currency => "Iceland Krona")
    Country.create( :name => "India", :currency => "Indian Rupee")
    Country.create( :name => "Indonesia", :currency => "Indonesian Rupiah")
    Country.create( :name => "Iran", :currency => "Iranian Rial")
    Country.create( :name => "Iraq", :currency => "Iraqi Dinar")
    Country.create( :name => "Israel", :currency => "Israeli New Shekel")
    Country.create( :name => "San Marino", :currency => "Italian Lira")
    Country.create( :name => "Jamaica", :currency => "Jamaica Dollar")
    Country.create( :name => "Japan", :currency => "Japanese Yen")
    Country.create( :name => "Jordan", :currency => "Jordanian Dinar")
    Country.create( :name => "Cambodia", :currency => "Kampuchean Riel")
    Country.create( :name => "Kazakhstan", :currency => "Kazakhstan Tenge")
    Country.create( :name => "Kenya", :currency => "Kenyan Shilling")
    Country.create( :name => "Korea-South", :currency => "Korean Won")
    Country.create( :name => "Kuwait", :currency => "Kuwaiti Dinar")
    Country.create( :name => "Laos", :currency => "Lao Kip")
    Country.create( :name => "Latvia", :currency => "Latvian Lats")
    Country.create( :name => "Lebanon", :currency => "Lebanese Pound")
    Country.create( :name => "Lesotho", :currency => "Lesotho Loti")
    Country.create( :name => "Liberia", :currency => "Liberian Dollar")
    Country.create( :name => "Libya", :currency => "Libyan Dinar")
    Country.create( :name => "Lithuania", :currency => "Lithuanian Litas")
    Country.create( :name => "Macau", :currency => "Macau Pataca")
    Country.create( :name => "Madagascar", :currency => "Malagasy Franc")
    Country.create( :name => "Malawi", :currency => "Malawi Kwacha")
    Country.create( :name => "Malaysia", :currency => "Malaysian Ringgit")
    Country.create( :name => "Maldives", :currency => "Maldive Rufiyaa")
    Country.create( :name => "Malta", :currency => "Maltese Lira")
    Country.create( :name => "Turkmenistan", :currency => "Manat")
    Country.create( :name => "Bosnia-Herzegovina", :currency => "Marka")
    Country.create( :name => "Mauritania", :currency => "Mauritanian Ouguiya")
    Country.create( :name => "Mauritius", :currency => "Mauritius Rupee")
    Country.create( :name => "Mexico", :currency => "Mexican Nuevo Peso")
    Country.create( :name => "Moldova", :currency => "Moldovan Leu")
    Country.create( :name => "Mongolia", :currency => "Mongolian Tugrik")
    Country.create( :name => "Morocco", :currency => "Moroccan Dirham")
    Country.create( :name => "Western Sahara", :currency => "Moroccan Dirham")
    Country.create( :name => "Mozambique", :currency => "Mozambique Metical")
    Country.create( :name => "Myanmar", :currency => "Myanmar Kyat")
    Country.create( :name => "Namibia", :currency => "Namibia Dollar")
    Country.create( :name => "Nepal", :currency => "Nepalese Rupee")
    Country.create( :name => "Netherlands Antilles", :currency => "Netherlands Antillean Guilder")
    Country.create( :name => "Cook Islands", :currency => "New Zealand Dollar")
    Country.create( :name => "Tokelau", :currency => "New Zealand Dollar")
    Country.create( :name => "New Zealand", :currency => "New Zealand Dollar")
    Country.create( :name => "Niue", :currency => "New Zealand Dollar")
    Country.create( :name => "Pitcairn Island", :currency => "New Zealand Dollar")
    Country.create( :name => "Nicaragua", :currency => "Nicaraguan Cordoba Oro")
    Country.create( :name => "Nigeria", :currency => "Nigerian Naira")
    Country.create( :name => "Korea-North", :currency => "North Korean Won")
    Country.create( :name => "Bouvet Island", :currency => "Norwegian Krone")
    Country.create( :name => "Norway", :currency => "Norwegian Krone")
    Country.create( :name => "Svalbard and Jan Mayen Islands", :currency => "Norwegian Krone")
    Country.create( :name => "Oman", :currency => "Omani Rial")
    Country.create( :name => "Pakistan", :currency => "Pakistan Rupee")
    Country.create( :name => "Panama", :currency => "Panamanian Balboa")
    Country.create( :name => "Papua New Guinea", :currency => "Papua New Guinea Kina")
    Country.create( :name => "Paraguay", :currency => "Paraguay Guarani")
    Country.create( :name => "Peru", :currency => "Peruvian Nuevo Sol")
    Country.create( :name => "Philippines", :currency => "Philippine Peso")
    Country.create( :name => "Poland", :currency => "Polish Zloty")
    Country.create( :name => "South Georgia & South Sandwich Islands", :currency => "Pound Sterling")
    Country.create( :name => "Guernsey", :currency => "Pound Sterling")
    Country.create( :name => "Great Britain", :currency => "Pound Sterling")
    Country.create( :name => "Isle of Man", :currency => "Pound Sterling")
    Country.create( :name => "U.K.", :currency => "Pound Sterling")
    Country.create( :name => "Jersey", :currency => "Pound Sterling")
    Country.create( :name => "Qatar", :currency => "Qatari Rial")
    Country.create( :name => "Romania", :currency => "Romanian Leu")
    Country.create( :name => "Russia", :currency => "Russian Ruble")
    Country.create( :name => "Rwanda", :currency => "Rwanda Franc")
    Country.create( :name => "Samoa", :currency => "Samoan Tala")
    Country.create( :name => "Saudi Arabia", :currency => "Saudi Riyal")
    Country.create( :name => "Seychelles", :currency => "Seychelles Rupee")
    Country.create( :name => "Sierra Leone", :currency => "Sierra Leone Leone")
    Country.create( :name => "Singapore", :currency => "Singapore Dollar")
    Country.create( :name => "Slovakia", :currency => "Slovak Koruna")
    Country.create( :name => "Slovenia", :currency => "Slovenian Tolar")
    Country.create( :name => "Solomon Islands", :currency => "Solomon Islands Dollar")
    Country.create( :name => "Kyrgyzstan", :currency => "Som")
    Country.create( :name => "Somalia", :currency => "Somali Shilling")
    Country.create( :name => "South Africa", :currency => "South African Rand")
    Country.create( :name => "South Sudan", :currency => "South Sudan Pound")
    Country.create( :name => "Sri Lanka", :currency => "Sri Lanka Rupee")
    Country.create( :name => "Saint Helena", :currency => "St. Helena Pound")
    Country.create( :name => "Sudan", :currency => "Sudanese Dinar")
    Country.create( :name => "Suriname", :currency => "Surinam Guilder")
    Country.create( :name => "Swaziland", :currency => "Swaziland Lilangeni")
    Country.create( :name => "Sweden", :currency => "Swedish Krona")
    Country.create( :name => "Liechtenstein", :currency => "Swiss Franc")
    Country.create( :name => "Switzerland", :currency => "Swiss Franc")
    Country.create( :name => "Syria", :currency => "Syrian Pound")
    Country.create( :name => "Taiwan", :currency => "Taiwan Dollar")
    Country.create( :name => "Tajikistan", :currency => "Tajik Ruble")
    Country.create( :name => "Tanzania", :currency => "Tanzanian Shilling")
    Country.create( :name => "Thailand", :currency => "Thai Baht")
    Country.create( :name => "Tonga", :currency => "Tongan Pa'anga")
    Country.create( :name => "Trinidad and Tobago", :currency => "Trinidad and Tobago Dollar")
    Country.create( :name => "Tunisia", :currency => "Tunisian Dollar")
    Country.create( :name => "Turkey", :currency => "Turkish Lira")
    Country.create( :name => "USA", :currency => "US Dollar")
    Country.create( :name => "Turks and Caicos Islands", :currency => "US Dollar")
    Country.create( :name => "British Indian Ocean Territory", :currency => "US Dollar")
    Country.create( :name => "Puerto Rico", :currency => "US Dollar")
    Country.create( :name => "Virgin Islands (USA)", :currency => "US Dollar")
    Country.create( :name => "Virgin Islands (British)", :currency => "US Dollar")
    Country.create( :name => "Palau", :currency => "US Dollar")
    Country.create( :name => "Guam (USA)", :currency => "US Dollar")
    Country.create( :name => "Micronesia", :currency => "US Dollar")
    Country.create( :name => "USA Minor Outlying Islands", :currency => "US Dollar")
    Country.create( :name => "Marshall Islands", :currency => "US Dollar")
    Country.create( :name => "American Samoa", :currency => "US Dollar")
    Country.create( :name => "Northern Mariana Islands", :currency => "US Dollar")
    Country.create( :name => "Uganda", :currency => "Uganda Shilling")
    Country.create( :name => "Ukraine", :currency => "Ukraine Hryvnia")
    Country.create( :name => "Uruguay", :currency => "Uruguayan Peso")
    Country.create( :name => "Uzbekistan", :currency => "Uzbekistan Sum")
    Country.create( :name => "Vanuatu", :currency => "Vanuatu Vatu")
    Country.create( :name => "Venezuela", :currency => "Venezuelan Bolivar")
    Country.create( :name => "Vietnam", :currency => "Vietnamese Dong")
    Country.create( :name => "Yemen", :currency => "Yemeni Rial")
    Country.create( :name => "China", :currency => "Yuan Renminbi")
    Country.create( :name => "Zambia", :currency => "Zambian Kwacha")
    Country.create( :name => "Zimbabwe", :currency => "Zimbabwe Dollar")

  end

  desc "Create Date Formats 'Default'"
  task :date_format => :environment do
    DateFormat.create(date_format: "Y-m-d", date_format_value: "%Y-%m-%d")
    DateFormat.create(date_format: "d/m/Y", date_format_value: "%d/%m/%Y")
    DateFormat.create(date_format: "d-m-Y", date_format_value: "%d-%m-%Y")
    DateFormat.create(date_format: "Y/m/d", date_format_value: "%Y/%m/%d")
    DateFormat.create(date_format: "M/d/Y", date_format_value: "%b/%d/%Y")
    DateFormat.create(date_format: "M-d-Y", date_format_value: "%b-%d-%Y")
    DateFormat.create(date_format: "d/M/Y", date_format_value: "%d/%b/%Y")
    DateFormat.create(date_format: "d-M-Y", date_format_value: "%d-%b-%Y")
    DateFormat.create(date_format: "Y-M-d", date_format_value: "%Y-%b-%d")
    DateFormat.create(date_format: "Y/M/d", date_format_value: "%Y/%b/%d")
    DateFormat.create(date_format: "d MM Y", date_format_value: "%d %B %Y")
    DateFormat.create(date_format: "MM d Y", date_format_value: "%B %d, %Y")
    DateFormat.create(date_format: "m/d/Y", date_format_value: "%m/%d/%Y")
    DateFormat.create(date_format: "m-Y-d", date_format_value: "%m-%Y-%d")
    DateFormat.create(date_format: "d/m/y", date_format_value: "%d/%m/%y")
    DateFormat.create(date_format: "d-m-y", date_format_value: "%d-%m-%y")
  end

  desc "Add default option settings"
  task :option_settings => :environment do
    OptionSetting.create(:country_id => "120", :time_zone => "(GMT+05:30) Kolkata", :currency => "Indian Rupee", :recruitment => false, :lv_atdn_mgmt => true, :appraisal => true, :training => false, :help_desk => false, :travel_cummute => false, :pf_applicable => true, :esi_applicable => true, :pt_applicable => true, :multi_state_pt => false, :multi_pt => false, :tds_applicable => false, :multi_branch => false, :multi_hr => false, :salary_calc => 'Jan/2012', :allow_brnch_admin => false, :approval_flow => false, :audit_trail => true, :remibursement => false, :bonus_and_exgratia => false, :gratuity => false, :loans_adv => false, :arrears => true, :attdn_intgration => false, :asset_tracker => false, :date_format=> "Y-m-d")
  end

  desc "Company document's file upload Type "
  task :upload_file_type => :environment do
    UploadFileType.create(:max_file_size => 5120, :file_type => "application/pdf,application/msword,application/vnd.ms-excel,text/plain")
  end

  desc "Create PF Group 'Default'"
  task :pf_group => :environment do
    PfGroup.create(:pf_group => 'Default', :pf_number => "123456", :db_file_code => 'IFC000', :extension => 1, :address => 'Bangalore')
  end

  desc "Create ESI Group 'Default'"
  task :esi_group => :environment do
    EsiGroup.create(:esi_group_name => 'Default', :esi_no => "123456", :esi_local_office => 'Bangalore', :address => 'Bangalore')
  end

  desc "Default values for PF"
  task :custom_setting_value => :environment do
    CustomSettingValue.create(:group => "PF Rate", :group_column => "epf", :group_column_value => "12")
    CustomSettingValue.create(:group => "PF Rate", :group_column => "cutoff", :group_column_value => "6500")
    CustomSettingValue.create(:group => "PF Rate", :group_column => "account_number_02", :group_column_value => "1.1")
    CustomSettingValue.create(:group => "PF Rate", :group_column => "account_number_21", :group_column_value => "0.5")
    CustomSettingValue.create(:group => "PF Rate", :group_column => "account_number_22", :group_column_value => "0.01")
    CustomSettingValue.create(:group => "PF Rate", :group_column => "pension_fund", :group_column_value => "3.67")
    CustomSettingValue.create(:group => "PF Rate", :group_column => "employer_epf", :group_column_value => "8.33")
    CustomSettingValue.create(:group => "PF Rate", :group_column => "round_off", :group_column_value => "Nearest Rupee")

    CustomSettingValue.create(:group => "ESI Rate", :group_column => "employee_rate", :group_column_value => "1.75")
    CustomSettingValue.create(:group => "ESI Rate", :group_column => "employer_rate", :group_column_value => "4.75")
    CustomSettingValue.create(:group => "ESI Rate", :group_column => "cut_off", :group_column_value => "15000")
    CustomSettingValue.create(:group => "ESI Rate", :group_column => "minimum_limit_dailywage", :group_column_value => "70")
    CustomSettingValue.create(:group => "ESI Rate", :group_column => "round_off", :group_column_value => "Higher Rupee")
  end

  desc "Add PT slabs for states"
  task :pt_slab => :environment do
    PtSlab.create(:state_id => 2,:minimum_sal_range=>0,:pt=>0)
    PtSlab.create(:state_id => 2,:minimum_sal_range=>5001,:pt=>60)
    PtSlab.create(:state_id => 2,:minimum_sal_range=>6001,:pt=>80)
    PtSlab.create(:state_id => 2,:minimum_sal_range=>10001,:pt=>100)
    PtSlab.create(:state_id => 2,:minimum_sal_range=>15001,:pt=>150)
    PtSlab.create(:state_id => 2,:minimum_sal_range=>20001,:pt=>200)
    PtSlab.create(:state_id => 10,:minimum_sal_range=>0,:pt=>0)
    PtSlab.create(:state_id => 10,:minimum_sal_range=>3000,:pt=>30)
    PtSlab.create(:state_id => 10,:minimum_sal_range=>5000,:pt=>60)
    PtSlab.create(:state_id => 10,:minimum_sal_range=>8000,:pt=>100)
    PtSlab.create(:state_id => 10,:minimum_sal_range=>10000,:pt=>150)
    PtSlab.create(:state_id => 10,:minimum_sal_range=>15000,:pt=>200)
    PtSlab.create(:state_id => 11,:minimum_sal_range=>0,:pt=>0)
    PtSlab.create(:state_id => 11,:minimum_sal_range=>3000,:pt=>20)
    PtSlab.create(:state_id => 11,:minimum_sal_range=>6000,:pt=>80)
    PtSlab.create(:state_id => 11,:minimum_sal_range=>9000,:pt=>150)
    PtSlab.create(:state_id => 11,:minimum_sal_range=>12000,:pt=>200)
    PtSlab.create(:state_id => 15,:minimum_sal_range=>0,:pt=>0)
    PtSlab.create(:state_id => 15,:minimum_sal_range=>10000,:pt=>150)
    PtSlab.create(:state_id => 15,:minimum_sal_range=>15000,:pt=>200)
    PtSlab.create(:state_id => 16,:minimum_sal_range=>0,:pt=>0)
    PtSlab.create(:state_id => 16,:minimum_sal_range=>12000,:pt=>120)
    PtSlab.create(:state_id => 16,:minimum_sal_range=>18000,:pt=>180)
    PtSlab.create(:state_id => 16,:minimum_sal_range=>30000,:pt=>300)
    PtSlab.create(:state_id => 16,:minimum_sal_range=>45000,:pt=>450)
    PtSlab.create(:state_id => 16,:minimum_sal_range=>60000,:pt=>600)
    PtSlab.create(:state_id => 16,:minimum_sal_range=>75000,:pt=>750)
    PtSlab.create(:state_id => 16,:minimum_sal_range=>100000,:pt=>1000)
    PtSlab.create(:state_id => 16,:minimum_sal_range=>125000,:pt=>1250)
    PtSlab.create(:state_id => 18,:minimum_sal_range=>0,:pt=>0)
    PtSlab.create(:state_id => 18,:minimum_sal_range=>10000,:pt=>83)
    PtSlab.create(:state_id => 18,:minimum_sal_range=>12500,:pt=>125)
    PtSlab.create(:state_id => 18,:minimum_sal_range=>15000,:pt=>208)
    PtSlab.create(:state_id => 19,:minimum_sal_range=>0,:pt=>0)
    PtSlab.create(:state_id => 19,:minimum_sal_range=>5000.01,:pt=>175)
    PtSlab.create(:state_id => 19,:minimum_sal_range=>10000.01,:pt=>200)
    PtSlab.create(:state_id => 29,:minimum_sal_range=>0,:pt=>0)
    PtSlab.create(:state_id => 29,:minimum_sal_range=>21001,:pt=>100)
    PtSlab.create(:state_id => 29,:minimum_sal_range=>30001,:pt=>235)
    PtSlab.create(:state_id => 29,:minimum_sal_range=>45001,:pt=>510)
    PtSlab.create(:state_id => 29,:minimum_sal_range=>60001,:pt=>760)
    PtSlab.create(:state_id => 29,:minimum_sal_range=>75001,:pt=>1095)
    PtSlab.create(:state_id => 32,:minimum_sal_range=>0,:pt=>0)
    PtSlab.create(:state_id => 32,:minimum_sal_range=>3001,:pt=>30)
    PtSlab.create(:state_id => 32,:minimum_sal_range=>5001,:pt=>40)
    PtSlab.create(:state_id => 32,:minimum_sal_range=>6001,:pt=>45)
    PtSlab.create(:state_id => 32,:minimum_sal_range=>7001,:pt=>50)
    PtSlab.create(:state_id => 32,:minimum_sal_range=>8001,:pt=>90)
    PtSlab.create(:state_id => 32,:minimum_sal_range=>9001,:pt=>110)
    PtSlab.create(:state_id => 32,:minimum_sal_range=>15001,:pt=>130)
    PtSlab.create(:state_id => 32,:minimum_sal_range=>25001,:pt=>150)
    PtSlab.create(:state_id => 32,:minimum_sal_range=>40001,:pt=>200)

  end

  desc "Run all bootstrapping tasks"
  task :all => [:default_user, :salary_head, :state, :attendance_configuration, :financial_institution, :classification_heading, :hr_category, :country, :option_settings, :upload_file_type, :pf_group, :esi_group, :custom_setting_value,:pt_slab,:date_format]
end
