require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MonthYearsController do

  # This should return the minimal set of attributes required to create a valid
  # MonthYear. As you add validations to MonthYear, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all month_years as @month_years" do
      month_year = MonthYear.create! valid_attributes
      get :index
      assigns(:month_years).should eq([month_year])
    end
  end

  describe "GET show" do
    it "assigns the requested month_year as @month_year" do
      month_year = MonthYear.create! valid_attributes
      get :show, :id => month_year.id
      assigns(:month_year).should eq(month_year)
    end
  end

  describe "GET new" do
    it "assigns a new month_year as @month_year" do
      get :new
      assigns(:month_year).should be_a_new(MonthYear)
    end
  end

  describe "GET edit" do
    it "assigns the requested month_year as @month_year" do
      month_year = MonthYear.create! valid_attributes
      get :edit, :id => month_year.id
      assigns(:month_year).should eq(month_year)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MonthYear" do
        expect {
          post :create, :month_year => valid_attributes
        }.to change(MonthYear, :count).by(1)
      end

      it "assigns a newly created month_year as @month_year" do
        post :create, :month_year => valid_attributes
        assigns(:month_year).should be_a(MonthYear)
        assigns(:month_year).should be_persisted
      end

      it "redirects to the created month_year" do
        post :create, :month_year => valid_attributes
        response.should redirect_to(MonthYear.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved month_year as @month_year" do
        # Trigger the behavior that occurs when invalid params are submitted
        MonthYear.any_instance.stub(:save).and_return(false)
        post :create, :month_year => {}
        assigns(:month_year).should be_a_new(MonthYear)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MonthYear.any_instance.stub(:save).and_return(false)
        post :create, :month_year => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested month_year" do
        month_year = MonthYear.create! valid_attributes
        # Assuming there are no other month_years in the database, this
        # specifies that the MonthYear created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MonthYear.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => month_year.id, :month_year => {'these' => 'params'}
      end

      it "assigns the requested month_year as @month_year" do
        month_year = MonthYear.create! valid_attributes
        put :update, :id => month_year.id, :month_year => valid_attributes
        assigns(:month_year).should eq(month_year)
      end

      it "redirects to the month_year" do
        month_year = MonthYear.create! valid_attributes
        put :update, :id => month_year.id, :month_year => valid_attributes
        response.should redirect_to(month_year)
      end
    end

    describe "with invalid params" do
      it "assigns the month_year as @month_year" do
        month_year = MonthYear.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MonthYear.any_instance.stub(:save).and_return(false)
        put :update, :id => month_year.id, :month_year => {}
        assigns(:month_year).should eq(month_year)
      end

      it "re-renders the 'edit' template" do
        month_year = MonthYear.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MonthYear.any_instance.stub(:save).and_return(false)
        put :update, :id => month_year.id, :month_year => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested month_year" do
      month_year = MonthYear.create! valid_attributes
      expect {
        delete :destroy, :id => month_year.id
      }.to change(MonthYear, :count).by(-1)
    end

    it "redirects to the month_years list" do
      month_year = MonthYear.create! valid_attributes
      delete :destroy, :id => month_year.id
      response.should redirect_to(month_years_url)
    end
  end

end
